name: CI-pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: execute latex
        run: docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "$PWD":/doc thomasweise/texlive make
      - run: sudo apt-get update && sudo apt-get install -y ghostscript 
      - name: compress pdf
        run: gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=sven_r_$(date +%Y_%m_%d).pdf resume.pdf
      - name: Archive pdf
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: resume sven rademakers
          path: |
            sven_r_*.pdf
            *.log

