name: CI-pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: generating pdf file
        run: make
      - name: Archive pdf
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: resume sven rademakers
          path: |
            sven_r_*.pdf
            *.log

